apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-test01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-sfs01
  serviceName: sfs-service01
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-sfs01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: sfs-vol01 # 컨테이너 내부에 마운트할 볼륨 정보
          mountPath: /mount01
  volumeClaimTemplates: # pvc 역할
  - metadata:
      name: sfs-vol01 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: pv-sfs-test01 # pv와 연결할 storageClass 이름
      resources:
        requests:
          storage: 20Mi # 20mb 용량 요청
# statefulset과 볼륨을 생성하는 yml 파일
