apiVersion: v1 # 파드의 경우
kind: Pod 
metadata: # 다른 오브젝트와 구분하는 식별자
  name: nginx01-volume-01
spec: # 앞으로 생성할 파드의 상태를 지정
  containers: # 파드에 포함될 컨테이너들을 지정
    - name: nginx-test01 
      image: nginx:latest
      volumeMounts: # 파드 내부의 디렉터리와 볼륨을 연결
      - name: empty-test01 # 컨테이너가 사용하게 될 볼륨 이름
        mountPath: /mount01 # 볼륨 마운트 경로
  volumes: # 파드 내부의 디렉터리와 볼륨을 연결
  - name: empty-test01 # 볼륨 이름 일치 
    emptyDir: {} # 빈 디렉터리를 생성, 추가 옵션을 사용x