version: "3"

services: 
  djangotest:
    build: ./myDjango03
    networks:
      - composenet01
    depends_on: # 먼저 실행할 녀석
      - postgrestest
    restart: always # 정지되면 재실행

  nginxtest:
    build: ./myNginx03
    networks:
      - composenet01
    ports: # 도커 호스트 포트: 컨테이너 포트
      - "8080:80"
    depends_on: # 실행 순서를 지정
      - djangotest
    restart: always

  postgrestest:
    build: ./myPostgres03
    networks:
      - composenet01
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - composevol01:/var/lib/postgresql/data
    restart: always

networks:
  composenet01:

volumes:
  composevol01:
  