apiVersion: v1 # 서비스의 경우
kind: Service
metadata: # 다른 오브젝트와 구분하는 식별자
  name: web-service
spec: # 앞으로 생성할 서비스의 상태를 지정
  selector: # 파드에 라벨을 붙이는 옵션(서비스가 관리할 파드 연결)
    app.kubernetes.io/name: web-deploy
  type: ClusterIP # 서비스의 타입을 지정
  ports: # 서비스가 사용할 포트를 지정
    - protocol: TCP
      port: 80
      